# Generated by Django 2.2.4 on 2021-05-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
